import type { Metadata } from 'next';
import Link from 'next/link';
import wikiRaw    from '../../../../public/wiki_data.json';
import mobFullRaw from '../../../../public/mob_full.json';
import mobDetailRaw from '../../../../public/mob_detail.json';
import SafeImg from '../../../components/SafeImg';
import CopyNavi from '../../../components/CopyNavi';
import { parseItemScript } from '../../../../lib/parse-script';
import styles from './item.module.css';

/* ── Types ── */
type ItemData  = { id: number; aegis: string; name: string; type: string; subtype: string; weight: number; buy: number; sell: number; slots: number };
type ShopEntry = { npc: string; map: string; x: number; y: number; price: number };
type Mob       = { Id: number; Name: string; Level: number; Element: string };
type Drop      = { id: number; basePct: number; pct: number };
type MobDetail = { drops: Drop[] };
type ItemDetail = {
  atk: number; matk: number; def: number;
  slots: number; reqLv: number; weaponLv: number;
  refineable: boolean; gradeable: boolean;
  jobs: Record<string, boolean>;
  location: Record<string, boolean>;
  script: string; equipScript: string; unequipScript: string;
};

/* ── Static data ── */
const wikiData   = wikiRaw      as unknown as { items: Record<string, ItemData>; shops: Record<string, ShopEntry[]> };
const mobFull    = mobFullRaw   as unknown as Mob[];
const mobDetail  = mobDetailRaw as unknown as Record<string, MobDetail>;

/* item_detail.json is generated by scripts/gen_item_detail.py — may be empty {} if not yet run */
let itemDetail: Record<string, ItemDetail> = {};
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  itemDetail = require('../../../../public/item_detail.json') as Record<string, ItemDetail>;
} catch { /* file doesn't exist yet */ }

/* ── Helpers ── */
function formatMapName(raw: string): string {
  return raw.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

const RATE_COLOR = (pct: number) =>
  pct >= 50 ? 'var(--jade-400)' : pct >= 5 ? 'var(--amber-400)' : 'var(--fg-muted)';

const WPN_LEVEL: Record<number, string> = { 1: 'I', 2: 'II', 3: 'III', 4: 'IV', 5: 'V' };

const LOCATION_LABEL: Record<string, string> = {
  HeadTop: 'Upper Head', HeadMid: 'Mid Head', HeadLow: 'Lower Head',
  Armor: 'Armor', RightHand: 'Right Hand', LeftHand: 'Left Hand / Shield',
  Garment: 'Garment', Shoes: 'Shoes',
  RightAccessory: 'Right Accessory', LeftAccessory: 'Left Accessory',
  BothHands: 'Both Hands', Both: 'Both Accessories',
  CostumeHeadTop: 'Costume Upper Head', CostumeGarment: 'Costume Garment',
};

function formatLocation(loc: Record<string, boolean>): string {
  return Object.entries(loc).filter(([, v]) => v)
    .map(([k]) => LOCATION_LABEL[k] ?? k.replace(/([A-Z])/g, ' $1').trim())
    .join(', ');
}

function formatJobs(jobs: Record<string, boolean>): string {
  const active = Object.keys(jobs).filter(k => jobs[k]);
  if (!active.length) return '';
  if (active.includes('All') || active.length > 18) return 'All Classes';
  return active.slice(0, 8).join(', ') + (active.length > 8 ? ` +${active.length - 8}` : '');
}

/* ── Metadata ── */
export const dynamicParams = true;
export async function generateStaticParams() { return []; }

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params;
  const item = wikiData.items[id];
  if (!item) return { title: 'Item Not Found — xRO Wiki' };
  return {
    title: `${item.name} — xRO Wiki`,
    description: `${item.name} (ID ${item.id}) en xRO — stats, effects, drops y NPCs.`,
  };
}

/* ── Page ── */
export default async function ItemPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const item = wikiData.items[id];

  if (!item) {
    return (
      <div className={styles.notFound}>
        <p>Item #{id} no encontrado.</p>
        <Link href="/wiki">← Volver a la wiki</Link>
      </div>
    );
  }

  const shops: ShopEntry[]  = wikiData.shops[id] ?? [];
  const detail: ItemDetail | undefined = itemDetail[id];

  const droppedBy = mobFull
    .filter(mob => mobDetail[String(mob.Id)]?.drops.some(d => d.id === item.id))
    .map(mob => {
      const drop = mobDetail[String(mob.Id)]!.drops.find(d => d.id === item.id)!;
      return { mob, basePct: drop.basePct, pct: drop.pct };
    })
    .sort((a, b) => b.pct - a.pct);

  const iconUrl  = `https://static.divine-pride.net/images/items/item/${item.id}.png`;
  const isEquip  = ['Weapon', 'Armor', 'ShadowGear'].includes(item.type);
  const isWeapon = item.type === 'Weapon';

  const scriptLines = parseItemScript(detail?.script ?? '');
  const equipLines  = parseItemScript(detail?.equipScript ?? '');
  const hasEffects  = scriptLines.length > 0 || equipLines.length > 0;

  const locStr  = detail?.location ? formatLocation(detail.location) : '';
  const jobsStr = detail?.jobs     ? formatJobs(detail.jobs) : '';

  return (
    <main className={styles.main}>
      {/* Breadcrumb */}
      <nav className={styles.breadcrumb}>
        <Link href="/">Inicio</Link><span>/</span>
        <Link href="/wiki">Wiki</Link><span>/</span>
        <Link href="/wiki?tab=items">Items</Link><span>/</span>
        <span>{item.name}</span>
      </nav>

      {/* Hero */}
      <section className={styles.hero}>
        <div className={styles.heroIcon}>
          <SafeImg src={iconUrl} alt={item.name} width={48} height={48} />
        </div>

        <div className={styles.heroInfo}>
          <div className={styles.heroMeta}>
            <span className={styles.heroId}>#{item.id}</span>
            <span className={styles.heroAegis}>{item.aegis}</span>
          </div>
          <h1 className={styles.heroName}>{item.name}</h1>
          <div className={styles.heroBadges}>
            <span className={styles.badge}>{item.type}{item.subtype ? ` · ${item.subtype}` : ''}</span>
            {(detail?.slots ?? item.slots) > 0 && (
              <span className={styles.badge}>
                {detail?.slots ?? item.slots} slot{(detail?.slots ?? item.slots) > 1 ? 's' : ''}
              </span>
            )}
            {detail?.refineable && <span className={styles.badge}>Refineable</span>}
            {detail?.gradeable  && <span className={styles.badge}>Gradeable</span>}
            {isWeapon && (detail?.weaponLv ?? 0) > 0 && (
              <span className={styles.badge}>Weapon Lv {WPN_LEVEL[detail!.weaponLv] ?? detail!.weaponLv}</span>
            )}
          </div>
        </div>

        {/* Stats column */}
        <div className={styles.heroPrices}>
          {isWeapon && (detail?.atk ?? 0) > 0 && (
            <div className={styles.priceItem}>
              <span className={styles.priceLabel}>ATK</span>
              <span className={styles.priceVal}>{detail!.atk}</span>
            </div>
          )}
          {isWeapon && (detail?.matk ?? 0) > 0 && (
            <div className={styles.priceItem}>
              <span className={styles.priceLabel}>MATK</span>
              <span className={styles.priceVal}>{detail!.matk}</span>
            </div>
          )}
          {isEquip && (detail?.def ?? 0) > 0 && (
            <div className={styles.priceItem}>
              <span className={styles.priceLabel}>DEF</span>
              <span className={styles.priceVal}>{detail!.def}</span>
            </div>
          )}
          {(detail?.reqLv ?? 0) > 0 && (
            <div className={styles.priceItem}>
              <span className={styles.priceLabel}>Min Lv</span>
              <span className={styles.priceVal}>{detail!.reqLv}</span>
            </div>
          )}
          <div className={styles.priceItem}>
            <span className={styles.priceLabel}>Buy</span>
            <span className={styles.priceVal}>{item.buy > 0 ? item.buy.toLocaleString() + ' z' : '—'}</span>
          </div>
          <div className={styles.priceItem}>
            <span className={styles.priceLabel}>Sell</span>
            <span className={styles.priceVal}>{item.sell > 0 ? item.sell.toLocaleString() + ' z' : '—'}</span>
          </div>
          <div className={styles.priceItem}>
            <span className={styles.priceLabel}>Weight</span>
            <span className={styles.priceVal}>{(item.weight / 10).toFixed(1)}</span>
          </div>
        </div>
      </section>

      {/* Equip info bar: location + jobs */}
      {isEquip && (locStr || jobsStr) && (
        <div className={styles.equipBar}>
          {locStr && (
            <div className={styles.equipBarItem}>
              <span className={styles.equipBarLabel}>Slot</span>
              <span className={styles.equipBarVal}>{locStr}</span>
            </div>
          )}
          {jobsStr && (
            <div className={styles.equipBarItem}>
              <span className={styles.equipBarLabel}>Classes</span>
              <span className={styles.equipBarVal}>{jobsStr}</span>
            </div>
          )}
        </div>
      )}

      {/* Effects card — full width above grid */}
      {hasEffects && (
        <section className={styles.effectsCard}>
          <h2 className={styles.effectsTitle}>Effects</h2>
          <ul className={styles.effectsList}>
            {scriptLines.map((line, i) => (
              <li key={i} className={styles.effectLine}>{line}</li>
            ))}
            {equipLines.map((line, i) => (
              <li key={`eq-${i}`} className={styles.effectLine}>{line}</li>
            ))}
          </ul>
        </section>
      )}

      <div className={styles.grid}>
        {/* Drops from */}
        <section className={styles.card}>
          <h2 className={styles.cardTitle}>
            Dropped By
            <span className={styles.cardHint}>{droppedBy.length} monsters</span>
          </h2>
          {droppedBy.length === 0 ? (
            <p className={styles.empty}>Not dropped by any monster.</p>
          ) : (
            <ul className={styles.mobList}>
              {droppedBy.map(({ mob, basePct, pct }) => (
                <li key={mob.Id}>
                  <Link href={`/wiki/mob/${mob.Id}`} className={styles.mobRow}>
                    <SafeImg
                      src={`https://static.divine-pride.net/images/mobs/png/${mob.Id}.png`}
                      alt={mob.Name} width={32} height={32}
                      className={styles.mobRowSprite}
                    />
                    <span className={styles.mobRowName}>{mob.Name}</span>
                    <span className={styles.mobRowLv}>Lv{mob.Level}</span>
                    <div className={styles.dropRates}>
                      <span style={{ color: RATE_COLOR(pct), fontWeight: 700, fontSize: '13px' }}>
                        {pct >= 100 ? '100%' : pct.toFixed(2) + '%'}
                      </span>
                      {pct !== basePct && (
                        <span className={styles.dropBase}>{basePct.toFixed(2)}%</span>
                      )}
                    </div>
                  </Link>
                </li>
              ))}
            </ul>
          )}
        </section>

        {/* NPC shops */}
        <section className={styles.card}>
          <h2 className={styles.cardTitle}>
            NPC Shops
            <span className={styles.cardHint}>{shops.length > 0 ? `${shops.length} NPCs` : 'none'}</span>
          </h2>
          {shops.length === 0 ? (
            <p className={styles.empty}>Not sold at any NPC shop.</p>
          ) : (
            <ul className={styles.shopList}>
              {shops.map((shop, i) => (
                <li key={i} className={styles.shopRow}>
                  <div className={styles.shopNpc}>
                    <Link href={`/wiki/npc/${encodeURIComponent(shop.npc)}`} className={styles.shopNpcName}>
                      {shop.npc}
                    </Link>
                    <div className={styles.shopNpcMapRow}>
                      <Link href={`/wiki/map/${shop.map}`} className={styles.shopNpcMap}>
                        {formatMapName(shop.map)}
                      </Link>
                      <CopyNavi map={shop.map} x={shop.x} y={shop.y} />
                    </div>
                  </div>
                  <span className={styles.shopPrice}>{shop.price.toLocaleString()} z</span>
                </li>
              ))}
            </ul>
          )}
        </section>
      </div>
    </main>
  );
}
